apiVersion: v1
kind: Service
metadata:
  name: document-processor
  labels:
    app.kubernetes.io/name: document-processor
spec:
  selector:
    app.kubernetes.io/name: document-processor
  ports:
    - name: http
      port: 8001
      targetPort: 8001
