apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yellowpad

labels:
  - pairs:
      app.kubernetes.io/part-of: yellowpad
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - redis/service.yaml
  - redis/deployment.yaml
  - minio/service.yaml
  - minio/statefulset.yaml
  - api-gateway/service.yaml
  - api-gateway/deployment.yaml
  - document-processor/service.yaml
  - document-processor/deployment.yaml
  - web-ui/service.yaml
  - web-ui/deployment.yaml
  - web-ui/ingress.yaml
